version: '3'
services:
    books:
        build:
            context: ../../
            dockerfile: ./tools/deploy/Dockerfile
        #command: python server.py
        ports:
            - '5000:5000'